# Generated by Django 6.0.5 on 2026-05-18 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_alter_category_category_name_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('Daraft', 'Draft'), ('Published', 'Published')], default='Draft', max_length=20),
        ),
    ]
