# Generated by Django 6.0.5 on 2026-05-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_heading', models.CharField(max_length=55)),
                ('about_description', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'About',
            },
        ),
    ]
